Event log and action queue
tim-hellhake/webthings-client pull request #3
Opened 2020-09-06 12:44 UTC by Galveston01

This proposes to add support for getting the event log (for a device or specific event) as well as action queue (equally for a device or a specific action). Furthermore, executing an action now returns an action executor (the same one that can afterwards be obtained through the action queue), which can then be used in order to cancel this action instance.

This pull request is based on #2.

2020-09-06 18:04 UTC, tim-hellhake commented
Can you please rebase the branch onto the lastest master?

2020-09-06 22:40 UTC, Galveston01 commented
Hope that did the job😅

2020-09-07 19:30 UTC, tim-hellhake reviewed
There seems to be a lot of duplicated code in the `href` functions.
I think I'll fix it after merging the PR.

2020-09-07 19:31 UTC, tim-hellhake commented
> Hope that did the job

It did :grimacing:

2020-09-07 20:04 UTC, tim-hellhake requested changes

2020-09-07 20:04 UTC, tim-hellhake commented on src/actionexecutor.ts
> +export class ActionExecutor {
I'm a bit unsure about the `Executor` part of the name.
The class represents a reference to a running action rather than something that executes the action.
What do you think about `ActionExecution`?

2020-09-07 20:04 UTC, tim-hellhake commented on src/action.ts
> +            return [];
I don't think this is necessary.
A `map` call on an empty array results in an empty array.

2020-09-07 20:04 UTC, tim-hellhake commented on src/event.ts
> +            return [];
Same here

2020-09-07 20:06 UTC, tim-hellhake commented
I'm curious.
What are your plans with this almost complete feature set? :grimacing:

2020-09-07 21:55 UTC, Galveston01 commented on src/actionexecutor.ts
> +export class ActionExecutor {
How about the proposed `ActionInstance` as well as `EventInstance`?

2020-09-07 21:55 UTC, Galveston01 commented
> I'm curious.
> What are your plans with this almost complete feature set?

I am currently working on an add-on to make it possible to use macros (kind of more complex rules formulated in a different format). For this, I had already implemented the new features from #1 and #2, but then thought it would be more reasonable to put these directly into your package. The features from this pull request however I honestly do not need (at least till now) and only added these for completeness^^

2020-09-07 21:57 UTC, tim-hellhake commented on src/actionexecutor.ts
> +export class ActionExecutor {
Sounds good

2020-09-07 22:00 UTC, merged

2020-09-07 22:04 UTC, Galveston01 commented
Oh, that was quick. Just created a commit here that removes the href redundancy😅

2020-09-07 22:16 UTC, tim-hellhake commented
> I am currently working on an add-on to make it possible to use macros

Sounds interesting.
I'm working on something similar.

> The features from this pull request however I honestly do not need

Even nicer

> Oh, that was quick. Just created a commit here that removes the href redundancysweat_smile

Would you mind opening a new PR? :sweat_smile: