Add support for global things socket (and maybe one or two other things)
tim-hellhake/webthings-client pull request #8
Opened 2020-11-04 20:51 UTC by bewee

Finally figured out how to find out when devices got added / removed.
I am not 100% certain whether this is the best possible solution, but it seemed to me like the most reasonable one: Since getting the device instances + their properties from the global webthings client requires a (likely redundant) call to getDevices (which is sometimes not even possible, specifically after thingRemoved), I decided to just emit the IDs of affected things as strings.

2020-11-04 21:16 UTC, bewee commented
Unfortunately, removing event subscriptions seems not to be possible yet. But that shouldn't be too much of a problem since one can simply dis- and reconnect.

2020-11-04 22:21 UTC, tim-hellhake requested changes
Looks good, just some small nitpicks.

2020-11-04 22:21 UTC, tim-hellhake commented on examples/monitor.js
> +    webThingsClient.connect().then(() => {
You can use `await` here to increase the readability

2020-11-04 22:21 UTC, tim-hellhake commented on src/webthings-client.ts
> +    private connection?: any;
Can you please add the type here?
The `websocket` package should export it.

2020-11-04 22:21 UTC, tim-hellhake commented on src/webthings-client.ts
> +import { client as WebSocketClient } from "websocket";
Single quotes :grimacing: 

```suggestion
import { EventEmitter } from 'events';
import { client as WebSocketClient } from 'websocket';
```

2020-11-04 23:02 UTC, bewee commented
Thanks for the quick feedback, these sound quite reasonable.
Since you definitely have a lot more experience with typescript than me: May I ask how I best find out a type that a package like e.g. websocket exports?  Right now I just skimmed the source code of the files in the websocket directory of the DefinitelyTyped repo. Is there any quicker way?

2020-11-04 23:05 UTC, bewee commented
Oh and I hope I didn't upset you somehow with the example file earlier (the 😬 got me thinking a little)

2020-11-04 23:16 UTC, tim-hellhake commented
> Thanks for the quick feedback, these sound quite reasonable.

:)

> Is there any quicker way?

I usually try to follow the type tree.
The connection comes from `webSocketClient.on('connect', connection => void)`.
If vscode already has the correct typing, you can jump into it with `Go to Type Definition`.

> Oh and I hope I didn't upset you somehow with the example file earlier (the :grimacing: got me thinking a little)

I'm glad that you mention it.
This was absolutely not intended.
How could I be upset about someone helping me to improve the library?
I just wanted it to sound a bit more relaxed.

2020-11-04 23:18 UTC, merged

2020-11-04 23:31 UTC, bewee commented
I'm relieved to hear that; I even googled the meaning of that emoji😅

> I usually try to follow the type tree.
> The connection comes from `webSocketClient.on('connect', connection => void)`.
> If vscode already has the correct typing, you can jump into it with `Go to Type Definition`.

Will try this out next time :)

2020-11-05 00:18 UTC, tim-hellhake commented
I added typescript-eslint and the eslint rules from the gateway.
If you have any violations try `npm run lint -- --fix` first.
I should deal with most of the warnings.

2020-11-05 00:19 UTC, tim-hellhake commented
Btw. Version `3.0.0` is now on NPM.